@startuml
hide empty description
[*] --> Starting 
Starting --> Active
Active --> Stopping
Stopping -> Stopped: allChildrenStopped
Active --> Disposing
Disposing --> Stopping
Paused --> Restart
Paused --> Active
Restart --> Starting
Paused --> Disposing
Stopped --> [*]
Active --> Errored
Errored --> Active
Errored --> Disposing
Errored --> Restart
Errored --> Paused
Restart --> Disposing

Active: processes\nmessages
Stopping: stop children,\nprocess buffered\nmessages
Stopped: run onStop,\nparent advised,\nremove this from\nparent, further\nmessages sent\nto dead letters
Paused: messages\nbuffered
Errored: handled by\nsupervisor
Starting: run preStart
Disposing: clear mailbox,\ndispose children

@enduml