@startuml
hide empty description
[*] --> Starting 
Starting --> Active
Active --> Stopping
Stopping -> Stopped
Active --> Disposed
Stopping --> Disposed
Stopped --> Disposed
Paused --> Restart
Paused --> Active
Restart --> Starting
Paused --> Disposed
Disposed --> [*]
Active --> Errored
Errored --> Active
Errored --> Disposed
Errored --> Restart
Errored --> Paused
Restart --> Disposed

Active: processes\nmessages
Stopping: stop has been called\nchildren will be stopped\nfirst
Stopped: onStop method run,\nmessages queued after\nthis point are sent to\nDeadLetter actor
Paused: messages\nbuffered
Disposed: mailbox cleared,\nnew messages\ndiscarded
Errored: handled by\nsupervisor
Restart: 

@enduml